# Generated by Django 3.2.9 on 2023-05-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_binary_directors_binary_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ott_plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=200, unique=True, verbose_name="URL (auto generated. Don't touch)")),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('images', models.ImageField(upload_to='pics')),
                ('f1', models.CharField(max_length=100)),
                ('f2', models.CharField(max_length=100)),
                ('f3', models.CharField(max_length=100)),
                ('amt', models.IntegerField(default=999)),
                ('added_desc', models.CharField(max_length=300)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('updatedTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
