# Generated by Django 3.2.9 on 2023-05-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_ott_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(default='', max_length=200)),
                ('fromCity', models.CharField(max_length=100)),
                ('toCity', models.CharField(max_length=100)),
                ('depatureDate', models.DateField()),
                ('days', models.IntegerField(default=1)),
                ('noOfRooms', models.IntegerField()),
                ('noOfAdults', models.IntegerField()),
                ('noOfChildren', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phoneNo', models.CharField(max_length=12)),
                ('amountPerPerson', models.IntegerField(default=0)),
                ('totalAmount', models.FloatField(default=0)),
                ('userName', models.CharField(default='', max_length=200)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
    ]
